#=========================== Filebeat inputs =============================
kafka.home: /usr/local/kafka
filebeat.inputs:
- type: log
  enabled: true
  paths:
    - ${kafka.home}/logs/server.log*
  multiline.pattern: ^\[
  multiline.negate: true
  multiline.match: after

#============================= Filebeat modules ===============================

filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

#==================== Elasticsearch template setting ==========================

setup.template.settings:
  index.number_of_shards: 1

#================================ Outputs =====================================

output.kafka:
  hosts: [kafka_broker_1:9092]
  topic: 'peter-log'
  partition.round_robin:
      reachable_only: false
  required_acks: 1
  compression: gzip
  max_message_bytes: 1000000

