version: '3'
services:
    broker:
        stdin_open: true
        tty: true
        build:
            context: .
            dockerfile: ./DockerfileBroker
            args:
                KAFKA_URL: http://apache.tt.co.kr/kafka/2.3.0/kafka_2.12-2.3.0.tgz
                KAFKA_PATH: /usr/local/kafka
        ports:
            - 9092:9092
    producer:
        stdin_open: true
        tty: true
        build:
            context: .
            dockerfile: ./DockerfileProducer
            args:
                KAFKA_URL: http://apache.tt.co.kr/kafka/2.3.0/kafka_2.12-2.3.0.tgz
                KAFKA_PATH: /usr/local/kafka
                FILEBEAT_URL: https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-7.4.2-amd64.deb
        volumes:
            - ./filebeat.yml:/etc/filebeat/filebeat.yml
        ports:
            - 19092:9092
        depends_on:
            - broker
    elasticsearch:
        image: elasticsearch:6.5.3
        ulimits:
            memlock:
                soft: -1
                hard: -1
        stdin_open: true
        tty: true
        ports:
          - 9200:9200
          - 9300:9300
        depends_on:
            - producer
    nifi:
        stdin_open: true
        tty: true
        build:
            context: .
            dockerfile: ./DockerfileNifi
            args:
                NIFI_URL: http://apache.tt.co.kr/nifi/1.10.0/nifi-1.10.0-bin.tar.gz
                NIFI_PATH: /usr/local/nifi
        ports:
            - 8080:8080
        depends_on:
            - elasticsearch 
    kibana:
        image: kibana:6.5.3
        ports:
          - 5601:5601
        depends_on: 
          - elasticsearch
          - nifi
volumes:
    broker: 
        driver: local
    producer:
        driver: local
    nifi:
        driver: local
    es:
        driver: local
